version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: bigdata-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - bigdata-net

volumes:
  mongo-data:

networks:
  bigdata-net:
    driver: bridge